name: Deploy Node App

on:
  workflow_dispatch:
    inputs:
      target_ref:
        description: 'Tag ou commit SHA para deploy (deixe em branco para usar main)'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.target_ref || 'main' }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar script de deploy
        run: ./deploy.sh
